2024-11-11 10:38:05,865 [INFO] USER:chavanshreyas_santos project.py:77:generate_project_structure LOG: Project task04 folder has been successfully created.
2024-11-11 10:38:05,865 [INFO] USER:chavanshreyas_santos helper.py:328:timed LOG: Stage project, elapsed time: 0:00:00.023631
2024-11-11 10:39:28,138 [INFO] USER:chavanshreyas_santos s3_resource.py:40:validate_bucket_name LOG: Starting validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2024-11-11 10:39:28,138 [INFO] USER:chavanshreyas_santos s3_resource.py:73:validate_bucket_name LOG: Finished validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2024-11-11 10:39:28,154 [INFO] USER:chavanshreyas_santos helper.py:514:convert LOG: Stripping course_id:SEP_JAP_4,course_type:stm,student_id:ddf81943,type:student from "," a bit..
2024-11-11 10:39:28,154 [INFO] USER:chavanshreyas_santos helper.py:518:convert LOG: Converting: course_id:SEP_JAP_4,course_type:stm,student_id:ddf81943,type:student to dict..
2024-11-11 10:39:28,154 [INFO] USER:chavanshreyas_santos helper.py:530:convert LOG: Converted to such a dict: {'course_id': 'SEP_JAP_4', 'course_type': 'stm', 'student_id': 'ddf81943', 'type': 'student'}
2024-11-11 10:39:30,449 [WARNING] USER:chavanshreyas_santos generator.py:76:generate_configuration_files LOG: The config_path property is not specified. The working directory is used
2024-11-11 10:39:30,449 [WARNING] USER:chavanshreyas_santos generator.py:93:generate_configuration_files LOG: The "project_path" property is not specified. The working directory will be used as a project path. To change the path, edit the syndicate.yml by path C:\Users\chavanshreyas_santos\Desktop\AWS tasks\lambda-function\task04\.syndicate-config-dev
2024-11-11 10:39:30,453 [INFO] USER:chavanshreyas_santos generator.py:155:generate_configuration_files LOG: Syndicate initialization has been completed. 
Set SDCT_CONF:
Unix: export SDCT_CONF="C:\Users\chavanshreyas_santos\Desktop\AWS tasks\lambda-function\task04\.syndicate-config-dev"
Windows: setx SDCT_CONF C:\Users\chavanshreyas_santos\Desktop\AWS tasks\lambda-function\task04\.syndicate-config-dev
2024-11-11 10:39:30,463 [INFO] USER:chavanshreyas_santos helper.py:328:timed LOG: Stage config, elapsed time: 0:00:02.309243
2024-11-11 14:29:58,947 [INFO] USER:chavanshreyas_santos project.py:77:generate_project_structure LOG: Project task04 folder has been successfully created.
2024-11-11 14:29:58,947 [INFO] USER:chavanshreyas_santos helper.py:328:timed LOG: Stage project, elapsed time: 0:00:00.013510
2024-11-11 14:34:25,341 [INFO] USER:chavanshreyas_santos s3_resource.py:40:validate_bucket_name LOG: Starting validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2024-11-11 14:34:25,341 [INFO] USER:chavanshreyas_santos s3_resource.py:73:validate_bucket_name LOG: Finished validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2024-11-11 14:34:25,341 [INFO] USER:chavanshreyas_santos helper.py:514:convert LOG: Stripping course_id:SEP_JAP_4,course_type:stm,student_id:ddf81943,type:student from "," a bit..
2024-11-11 14:34:25,341 [INFO] USER:chavanshreyas_santos helper.py:518:convert LOG: Converting: course_id:SEP_JAP_4,course_type:stm,student_id:ddf81943,type:student to dict..
2024-11-11 14:34:25,342 [INFO] USER:chavanshreyas_santos helper.py:530:convert LOG: Converted to such a dict: {'course_id': 'SEP_JAP_4', 'course_type': 'stm', 'student_id': 'ddf81943', 'type': 'student'}
2024-11-11 14:34:27,800 [WARNING] USER:chavanshreyas_santos generator.py:76:generate_configuration_files LOG: The config_path property is not specified. The working directory is used
2024-11-11 14:34:27,802 [WARNING] USER:chavanshreyas_santos generator.py:93:generate_configuration_files LOG: The "project_path" property is not specified. The working directory will be used as a project path. To change the path, edit the syndicate.yml by path C:\Users\chavanshreyas_santos\Desktop\AWS tasks\lambda-function\task04\.syndicate-config-dev
2024-11-11 14:34:27,809 [INFO] USER:chavanshreyas_santos generator.py:155:generate_configuration_files LOG: Syndicate initialization has been completed. 
Set SDCT_CONF:
Unix: export SDCT_CONF="C:\Users\chavanshreyas_santos\Desktop\AWS tasks\lambda-function\task04\.syndicate-config-dev"
Windows: setx SDCT_CONF C:\Users\chavanshreyas_santos\Desktop\AWS tasks\lambda-function\task04\.syndicate-config-dev
2024-11-11 14:34:27,813 [INFO] USER:chavanshreyas_santos helper.py:328:timed LOG: Stage config, elapsed time: 0:00:02.471114
2024-11-11 22:01:56,920 [INFO] USER:chavanshreyas_santos project.py:77:generate_project_structure LOG: Project task05 folder has been successfully created.
2024-11-11 22:01:56,920 [INFO] USER:chavanshreyas_santos helper.py:328:timed LOG: Stage project, elapsed time: 0:00:00.015629
2024-11-11 22:05:17,536 [INFO] USER:chavanshreyas_santos s3_resource.py:40:validate_bucket_name LOG: Starting validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2024-11-11 22:05:17,536 [INFO] USER:chavanshreyas_santos s3_resource.py:73:validate_bucket_name LOG: Finished validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2024-11-11 22:05:17,536 [INFO] USER:chavanshreyas_santos helper.py:514:convert LOG: Stripping course_id:SEP_JAP_4,course_type:stm,student_id:ddf81943,type:student from "," a bit..
2024-11-11 22:05:17,536 [INFO] USER:chavanshreyas_santos helper.py:518:convert LOG: Converting: course_id:SEP_JAP_4,course_type:stm,student_id:ddf81943,type:student to dict..
2024-11-11 22:05:17,536 [INFO] USER:chavanshreyas_santos helper.py:530:convert LOG: Converted to such a dict: {'course_id': 'SEP_JAP_4', 'course_type': 'stm', 'student_id': 'ddf81943', 'type': 'student'}
2024-11-11 22:05:21,256 [ERROR] USER:chavanshreyas_santos helper.py:110:wrapper LOG: Error occurred: An error occurred (SignatureDoesNotMatch) when calling the GetCallerIdentity operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
2024-11-11 22:05:21,256 [ERROR] USER:chavanshreyas_santos helper.py:111:wrapper LOG: Traceback:
 Traceback (most recent call last):
  File "C:\Users\chavanshreyas_santos\AppData\Roaming\Python\Python312\site-packages\syndicate\connection\helper.py", line 96, in wrapper
    return handler_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chavanshreyas_santos\AppData\Roaming\Python\Python312\site-packages\syndicate\connection\sts_connection.py", line 83, in get_caller_identity
    return self.client.get_caller_identity()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chavanshreyas_santos\AppData\Roaming\Python\Python312\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chavanshreyas_santos\AppData\Roaming\Python\Python312\site-packages\botocore\client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the GetCallerIdentity operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

2024-11-11 22:05:21,256 [ERROR] USER:chavanshreyas_santos generator.py:70:generate_configuration_files LOG: Invalid credentials provided, please specify the correct one
2024-11-11 22:05:21,256 [ERROR] USER:chavanshreyas_santos generator.py:72:generate_configuration_files LOG: Error while account_id obtaining
Traceback (most recent call last):
  File "C:\Users\chavanshreyas_santos\AppData\Roaming\Python\Python312\site-packages\syndicate\core\conf\generator.py", line 67, in generate_configuration_files
    caller_identity = sts.get_caller_identity()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chavanshreyas_santos\AppData\Roaming\Python\Python312\site-packages\syndicate\connection\helper.py", line 112, in wrapper
    raise e
  File "C:\Users\chavanshreyas_santos\AppData\Roaming\Python\Python312\site-packages\syndicate\connection\helper.py", line 96, in wrapper
    return handler_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chavanshreyas_santos\AppData\Roaming\Python\Python312\site-packages\syndicate\connection\sts_connection.py", line 83, in get_caller_identity
    return self.client.get_caller_identity()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chavanshreyas_santos\AppData\Roaming\Python\Python312\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chavanshreyas_santos\AppData\Roaming\Python\Python312\site-packages\botocore\client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the GetCallerIdentity operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
2024-11-11 22:46:40,226 [INFO] USER:chavanshreyas_santos s3_resource.py:40:validate_bucket_name LOG: Starting validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2024-11-11 22:46:40,226 [INFO] USER:chavanshreyas_santos s3_resource.py:73:validate_bucket_name LOG: Finished validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2024-11-11 22:46:40,226 [INFO] USER:chavanshreyas_santos helper.py:514:convert LOG: Stripping course_id:SEP_JAP_4,course_type:stm,student_id:ddf81943,type:student from "," a bit..
2024-11-11 22:46:40,226 [INFO] USER:chavanshreyas_santos helper.py:518:convert LOG: Converting: course_id:SEP_JAP_4,course_type:stm,student_id:ddf81943,type:student to dict..
2024-11-11 22:46:40,226 [INFO] USER:chavanshreyas_santos helper.py:530:convert LOG: Converted to such a dict: {'course_id': 'SEP_JAP_4', 'course_type': 'stm', 'student_id': 'ddf81943', 'type': 'student'}
2024-11-11 22:46:42,689 [WARNING] USER:chavanshreyas_santos generator.py:76:generate_configuration_files LOG: The config_path property is not specified. The working directory is used
2024-11-11 22:46:42,689 [WARNING] USER:chavanshreyas_santos generator.py:93:generate_configuration_files LOG: The "project_path" property is not specified. The working directory will be used as a project path. To change the path, edit the syndicate.yml by path C:\Users\chavanshreyas_santos\Desktop\AWS tasks\lambda-function\task05\.syndicate-config-dev
2024-11-11 22:46:42,689 [INFO] USER:chavanshreyas_santos generator.py:155:generate_configuration_files LOG: Syndicate initialization has been completed. 
Set SDCT_CONF:
Unix: export SDCT_CONF="C:\Users\chavanshreyas_santos\Desktop\AWS tasks\lambda-function\task05\.syndicate-config-dev"
Windows: setx SDCT_CONF C:\Users\chavanshreyas_santos\Desktop\AWS tasks\lambda-function\task05\.syndicate-config-dev
2024-11-11 22:46:42,705 [INFO] USER:chavanshreyas_santos helper.py:328:timed LOG: Stage config, elapsed time: 0:00:02.479291
